export { default as Login } from "./Login"
export { default as Main } from "./Main"
export { default as Cadastro } from "./Cadastro"
export { default as Genero } from "./Genero"
export { default as GeneroStore } from "./Genero/store"
export { default as Filme } from "./Filme"
export { default as FilmeStore } from "./Filme/store"